#!/bin/sh
source $GAAMPSCRIPTS/routines

cp ../110-esp/mol.xpsf .
cp ../030-generate_structure/mol.prm .
cp ../030-generate_structure/mol.rtf .
cp ../110-esp/mol-esp.dat .
cp ../110-esp/mol-opt.crd .
cp ../110-esp/elem-list.txt .

# Generate fit-mol.conf
cat ../030-generate_structure/equiv-org.txt >> fit-mol.conf
cat ../030-generate_structure/neutral.txt >> fit-mol.conf
cat ../030-generate_structure/fixq.txt >> fit-mol.conf

echo "E14FAC $E14FAC" >> fit-mol.conf
echo "netcharge $NetCharge" >> fit-mol.conf

echo "w_H_Donor_Acceptor $w_H_Donor_Acceptor" >> fit-mol.conf
echo "w_charge $w_charge" >> fit-mol.conf
echo "w_water_E_min $w_water_E_min" >> fit-mol.conf
echo "w_water_R_min $w_water_R_min" >> fit-mol.conf
echo "w_alpha $w_alpha" >> fit-mol.conf
echo "w_thole $w_thole" >> fit-mol.conf

echo "FILE_FORCE_FIELD    mol.prm" >> fit-mol.conf
echo "FILE_PSF            mol.xpsf" >> fit-mol.conf
echo "FILE_CRD            mol-opt.crd" >> fit-mol.conf
echo "FILE_pot0           mol-esp.dat" >> fit-mol.conf 
/bin/grep "    X= " ../110-esp/cal-esp.out | /usr/bin/head -n 1 | /bin/awk '{print "DIPOLE_QM " $2 "  "  $4 "   " $6 "   " $8}' >> fit-mol.conf

Gexe fitcharge fit-mol.conf 

Gexe update-xpsf

