#!/bin/sh
source $GAAMPSCRIPTS/routines

cp ../031-generate_drude/drude-mol.xpsf .
cp ../031-generate_drude/drude-mol.prm .
cp ../031-generate_drude/drude-mol.rtf .
cp ../111-esp_drude/mol-esp-pert.dat .
cp ../111-esp_drude/mol-esp-pot0.dat .
cp ../111-esp_drude/qpos.all .
cp ../111-esp_drude/elem-list.txt .

cat ../030-generate_structure/equiv-org.txt >> drude-fit-mol.conf
cat ../030-generate_structure/neutral.txt >> drude-fit-mol.conf
cat ../030-generate_structure/fixq.txt >> drude-fit-mol.conf
echo "E14FAC $E14FAC" >> drude-fit-mol.conf
echo "netcharge $NetCharge" >> drude-fit-mol.conf
echo "w_H_Donor_Acceptor $w_H_Donor_Acceptor" >> drude-fit-mol.conf
echo "w_charge $w_charge" >> drude-fit-mol.conf
echo "w_water_E_min $w_water_E_min" >> drude-fit-mol.conf
echo "w_water_R_min $w_water_R_min" >> drude-fit-mol.conf
echo "w_alpha $w_alpha" >> drude-fit-mol.conf
echo "w_thole $w_thole" >> drude-fit-mol.conf
#echo "w_H_Donor_Acceptor $w_H_Donor_Acceptor" >> drude-fit-mol.conf
#echo "w_charge $w_charge" >> drude-fit-mol.conf
#echo "w_water_E_min $w_water_E_min" >> drude-fit-mol.conf
#echo "w_water_R_min $w_water_R_min" >> drude-fit-mol.conf
#echo "w_alpha $w_alpha" >> drude-fit-mol.conf
#echo "w_thole $w_thole" >> drude-fit-mol.conf

##echo "constrain_CG 6 0.0" >> drude-fit-mol.conf

##echo "FILE_CRD            mol-opt.crd" >> drude-fit-mol.conf
echo "FILE_FORCE_FIELD    drude-mol.prm" >> drude-fit-mol.conf
echo "FILE_PSF            drude-mol.xpsf" >> drude-fit-mol.conf
echo "FILE_pot0           mol-esp-pot0.dat" >> drude-fit-mol.conf
echo "FILE_pot            mol-esp-pert.dat" >> drude-fit-mol.conf
echo "FILE_qpos           qpos.all" >> drude-fit-mol.conf
echo "
To_Fit_Aniso                            # To fit anisotrpy parameters or not
To_Use_Miller_Alpha                     # To use Miller's alpha as the target to constrain, otherwise use alpha in xpsf as the target 
" >> drude-fit-mol.conf
/bin/grep "    X= " ../111-esp_drude/cal-esp.out | /usr/bin/head -n 1 | /bin/awk '{print "DIPOLE_QM " $2 "  "  $4 "   " $6 "   " $8}' >> drude-fit-mol.conf


Gexe drude-scale-alpha drude-mol.xpsf 0.65

Gexe drude-fitcharge drude-fit-mol.conf

Gexe drude-gen_xpsf drude-esp-mol.rtf drude-esp-mol.xpsf MOL TEST

exit 0
